### PR TITLE
Update to newer versions of our underlying eslint configs

### PR DESCRIPTION
**Pull request by luma**
**What?**

Update to newer versions of our underlying eslint configs

**Why?**

We're significantly behind and are missing linting rules for newer es features (+ newer React).

### CODE REVIEW

**Comment by autopilot-pr-clerk** [comment]
#### Reviewer Checklist

- [ ] The JIRA ticket is present on this PR.
- [ ] This change is understandable or well documented.
- [ ] This PR follows the PR template.
- [ ] This PR adds or updates tests for each behaviour in this PR.

Please double check that the above are all checked or that the reasons they are not fulfiled have been justified then click the button below:

[Approve PR]( http://autopilot-pr-clerk.herokuapp.com/review/autopilothq/eslint-config-autopilot/1 )

**Review by Draal — APPROVED** [review]
lgtm

**Comment by autopilot-pr-clerk** [comment]
Nice work! The PR is now approved by two people, and should the tests pass, we
can merge it!

**Comment by autopilot-pr-clerk** [comment]
Nice work! The PR is now approved by two people, and should the tests pass, we
can merge it!

**Pull request merged**
